### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by yukosgiti** [jonhoo/roget#15]
Hey, I created a repository [for wordle tests](https://github.com/yukosgiti/wordle-tests). You mentioned wanting to improve the tests for the matcher. Can also be useful for benchmarking purposes.

I tried to have it contain the minimum amount of test cases for every possible checking condition.

(I'm newly learning Rust and  your streams are very helpful. I generated the files with Rust as well. Tears were involved also the borrow checker is a bully!)

**Comment by jonhoo** [comment]
Nice! Just added a test suite that runs all of them :tada:
